### PR TITLE
added MS Teams

### PR DESCRIPTION
**Pull request by dourosdimitris**

### CODE REVIEW

**Comment by kytta** [comment]
Please refrain from pushing multiple features in a single PR. Keep MS Teams in this PR and create a separate one for Web Share API 🙏🏻

**Comment by dourosdimitris** [comment]
Sorry for the inconvenience. I don't have time to properly PR, etc.
MS Teams and WebShare API are ready on my fork. You can implement/merge them properly if you want.
Thanks!

**Comment by kytta** [comment]
Okay, I'll have a look and merge them separately. I hope I can get this out before the end of the week.

**Comment by dourosdimitris** [comment]
No need to rush. Thanks!

**Comment by kytta** [comment]
Merged in #66 in #67. Will release on npm shortly after

**Comment by kytta** [comment]
Released in [v2.2.0](https://github.com/kytta/shareon/releases/tag/v2.2.0) 🎉

**Pull request closed without merging**
