### PR TITLE
Add Web Share API button

### LINKED ISSUE #63: Add "Share" button [sic]
On supported devices (which includes mobile browsers, Chromium and Edge on Windows, and Safari), there is the Web Share API. In particular, [`navigator.share()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) allows for showing a share popup of the OS, allowing to share the link to other apps we might not support: SMS messengers, Mastodon clients, etc. One can use [`navigator.canShare()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare) to hide the button on unsupported devices.

- [ ] pick an icon
- [ ] implement method, similar to how "Copy URL" works

### PR DESCRIPTION
**Pull request by kytta**
This PR includes code by @dourosdimitris from #64, more specifically 63581855a8cc73b1bba707f9c99594e6ad70d830 with some other fixes (icon, script).

Closes #63

### CODE REVIEW

**Comment by kytta** [comment]
Released in [v2.2.0](https://github.com/kytta/shareon/releases/tag/v2.2.0) 🎉

**Comment by dourosdimitris** [comment]
Hello, thanks for the PRs!
Seems there is an issue with the WebShare SVG.
https://picallow.com/wp-content/uploads/2023/07/2023-07-18_64b6c08182904_svg_issue.png

**Comment by kytta** [comment]
> Seems there is an issue with the WebShare SVG.

This should have been fixed in v2.2.2 via #71. Try clearing the cache in your browser, it may still load the version v2.2.1. I'll try to invalidate the cache on jsDelivr's side

**Comment by dourosdimitris** [comment]
I don't think it's the browser cache. Tried the official https://shareon.js.org/ with Chrome and Firefox Focus and the web-share icon is not displayed. Also pinned CDN to v2.2.2 explicitly and doesn't work either. 
Maybe it's an svg issue.

**Comment by dourosdimitris** [comment]
It's definetely an SVG issue.
Tried it here: https://www.svgviewer.dev/.
There is definetely an issue at `stroke='%2523fff'`, it's a error in encoding.

**Pull request merged**
